notifications:
  email: false

dist: bionic

language: c
compiler: gcc

git:
  depth: 3

addons:
  apt:
    packages:
      - autopoint
      - ca-certificates
      - gettext
      - gpgsm
      - graphviz
      - jimsh
      - libdb-dev
      - libgdbm-dev
      - libgnutls28-dev
      - libgpgme11-dev
      - libgss-dev
      - libidn2-0-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.2-dev
      - liblz4-dev
      - libncursesw5-dev
      - libnotmuch-dev
      - libpcre2-dev
      - libqdbm-dev
      - librocksdb-dev
      - libsasl2-dev
      - libslang2-dev
      - libssl-dev
      - libtdb-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - libzstd-dev
      - lua5.2
  coverity_scan:
    project:
      name: "neomutt/neomutt"
      description: "Teaching an Old Dog New Tricks"
    notification_email: rich@flatcap.org
    build_command_prepend: "./configure $OPTS"
    build_command: "make"
    branch_pattern: coverity

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "akQWaCea8IiHqHL6TWz6nBJF1aqU/u2O4MixUzsxNYckIqJbEo/r3UxIrsMFlL7/rNeI+cGOX9VtFGd9vbi04dFcqRSgQzsBCJ3O10zsfp29+KVGScPOWsIRs0zuqlSMKixCKjdlSWjaZpT+hFFjc9vVJdvZRln8ZqwbaQNTIeCg5QoOjYi5zCaV7IdwUgTfGKy3p/aG2v8uuvNcWL2EZEL3JEerIwOaE9IMF+2y6Z2b+kAU5zgaPF/mPz4yiIV6K7HuP0hdqiUqBJfnCSk7XrMyQVZAzcmlOSRyE6niDdZcvjedCnRR4M67gGgF0818et662YzXpdOOClRuGBeJff5fxnw7uT1xBWXHQ4z4rsgrDzLTHecdrlLAb7ZNaoxLKQyvZSysJ2GZdrzF4W5QluKIPbAuxdeiR5EdU/OTEhBsLmTPGv7L5f+hRTHfD+K/QhIZ/BYKP2pXlJFNEh4uuL5ljenJoAt405dqwzfWckF0j26vcP7+wW/qhpsXN0ToofmoNWPYPD8WD6vpSjk9WgFl1eZNSrTG51VMZKgUw2FsTNys7FhDpLaSJzNvC1PiKVSAxyo3gKP8fHzx0aJY0odyPM4ccLArkTgH2c3NBaHvhtgwFrVdXqoORmSrovF1FIOBqG6FCN1xrqtJ3qHSmU+NulpmODIbInlSrfR4okU="
  matrix:
    - OPTS="--autocrypt --bdb --disable-doc --disable-idn --fmemopen --gdbm --gnutls --gpgme --gss --homespool --idn2 --kyotocabinet --lmdb --lua --lz4 --mixmaster --notmuch --pcre2 --qdbm --rocksdb --sasl --tdb --tokyocabinet --with-domain=example.com --with-lock=fcntl --with-ui=ncurses --zlib --zstd"

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi

